### ISSUE TITLE
slackerduty

### ISSUE THREAD

**Issue by CGA1123** [CGA1123/bissy-api#4]
slackerduty but in go 🤷‍♂️ 

Some things:
- Remove user-specific notification options, send only to channels
- Implement App Home (what should be on it?)
- Add more specific integration functionality? (bugsnag snoozing?)
- More lightweight forwarding that links to original message

**Comment by CGA1123** [comment]
Couple features:
- Bugsnag: Snoozing from Slack
- Bugsnag: Snoozing w/ comment from Slack
- Capturing Entrypoints
- Auto/Suggested Forwarding
- Forwarding w/ messages
- Bugsnag: Linking to VCS?

**Comment by CGA1123** [comment]
## TODO
- [ ] Basic Pagerduty Functionality (Ack/Resolve)
- [ ] Forwarding (lightweight)
- [ ] Honeycomb integration (same as currently)
- [ ] Bugsnag integration (same as currently)
- [ ] Bugsnag integration -- entrypoint fetching
- [ ] Bugsnag integration -- entrypoint attribution (forwarding)
- [ ] Bugsnag integration -- comment on forward
- [ ] Bugsnag integration -- Snoozing
